// leave off @2x/@3x
const images = {
  splashImage: require('../Images/splash.jpg'),
  bgImage: require('../Images/starup-bg.jpg'),
  fbBtnImage: require('../Images/fb-btn.png'),
  googleBtnImage: require('../Images/google+-btn.png'),
  talkBtnImage: require('../Images/kakaotalk-btn.png'),
  fbLogo: require('../Images/facebook-letter-logo.png'),
  googleLogo: require('../Images/google-plus.png'),
  talkLogo: require('../Images/kakaotalk.png'),
  productImage: require('../Images/product.jpg'),
  barcodeImage: require('../Images/barcode.png'),
  searchIcon: require('../Images/search.png'),
  searchIconGrey: require('../Images/search-icon.png'),
  profileIcon: require('../Images/user.png'),
  dropDownIcon: require('../Images/drop-down-arrow.png'),
  rigthArrowIcon: require('../Images/right-arrow.png'),
  crossIcon: require('../Images/cross.jpg'),
  rightArrowIcon: require('../Images/arrow-right.png'),
  selectedHomeIcon: require('../Images/home-icon-hover.png'),
  unSelectedHomeIcon: require('../Images/home-icon.png'),
  selectedCategoryIcon: require('../Images/category-icon-hover.png'),
  unSelectedCategoryIcon: require('../Images/category-icon.png'),
  selectedProductIcon: require('../Images/add-pro-icon-hover.png'),
  unSelectedProductIcon: require('../Images/add-pro-icon.png'),
  selectedMemberIcon: require('../Images/member-icon-hover.png'),
  unSelectedMemberIcon: require('../Images/member-icon.png'),
  selectedSettingsIcon: require('../Images/setting-icon-hover.png'),
  unSelectedSettingsIcon: require('../Images/setting-icon.png'),
  InviteLink: require('../Images/unlink.png'),
  contactBook: require('../Images/contacts.png'),
  crossBtn: require('../Images/cross1.png'),
  addUser: require('../Images/add-user-button.png'),
  cart: require('../Images/cartWhite.png'),
  whiteRightarrow: require('../Images/next.png'),
  editProfile: require('../Images/profile_edit.png'),
  editProduct: require('../Images/edit_product.png'),
  notification: require('../Images/notification.png'),
  notifing: require('../Images/boy.png'),
}

export default images;
